################################################################################
#
# Node Controller configuration
#

- name: Configure eucalyptus.conf
  template: src=eucalyptus.conf.j2 dest={{ euca_conf_file_path }}
  tags:
  - euca_config
  - nc

- name: Remove default libvirt artifacts
  shell: virsh net-destroy default ; virsh net-undefine default
  tags:
  - nc
  ignore_errors: true

- name: Restart libvirtd
  service: name=libvirtd state=restarted
  tags:
  - nc

- name: Restart network service to apply bridge settings
  service: name=network state=restarted
  tags:
  - nc
  - net_init

- name: Get new info on the system
  setup:
  tags:
  - nc

- name: Display Bride info
  debug: msg="{{hostvars[inventory_hostname]['ansible_br' +  bridge_number|string] }}"
  tags:
  - nc
